# Generated by Django 5.0.2 on 2024-02-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
