# Generated by Django 5.0.2 on 2024-02-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_login_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='district',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='district',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='house_name',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='place',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='house_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='place',
        ),
    ]
