# Generated by Django 5.0.2 on 2024-02-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_rename_district_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
    ]
