# Generated by Django 5.0.2 on 2024-03-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
