# Generated by Django 5.0.2 on 2024-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='detail1',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='detail2',
            field=models.CharField(default='b', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='detail3',
            field=models.CharField(default='c', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='detail4',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='detail5',
            field=models.CharField(default='e', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='detail6',
            field=models.CharField(default='g', max_length=100),
            preserve_default=False,
        ),
    ]
