# Generated by Django 5.0.2 on 2024-03-18 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_remove_customer_detail1_remove_customer_detail2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('pay_id', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.customer')),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
