# Generated by Django 5.0.2 on 2024-03-18 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('acc_number', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
