# Generated by Django 5.0.2 on 2024-03-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='make_order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('CUSTOMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.customer')),
                ('PRODUCT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.product')),
            ],
            options={
                'db_table': 'make_order',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='ORDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.make_order'),
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
