# Generated by Django 5.0.2 on 2024-03-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_make_order_alter_payment_order_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='amount',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
