# Generated by Django 5.0.2 on 2024-03-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_make_order_amount_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_allot',
            fields=[
                ('vehicle_allot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.make_order')),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
                ('VEHICLE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.vehicle')),
            ],
            options={
                'db_table': 'vehicle_allot',
            },
        ),
    ]
