# Generated by Django 5.0.2 on 2024-03-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_vehicle_allot'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
