# Generated by Django 5.0.2 on 2024-03-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_complaint_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_order',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
