# Generated by Django 5.0.2 on 2024-03-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0024_alter_make_order_amount_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='worksite',
            fields=[
                ('worksite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('worksite_location', models.CharField(max_length=100)),
                ('product_used', models.CharField(max_length=100)),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('Remark', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'worksite',
            },
        ),
    ]
