# Generated by Django 5.0.2 on 2024-03-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0025_worksite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksite',
            old_name='Remark',
            new_name='remark',
        ),
    ]
