# Generated by Django 5.0.2 on 2024-03-25 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0027_rename_photo1_worksite_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksite',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.product'),
        ),
    ]
