# Generated by Django 5.0.2 on 2024-03-25 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_worksite_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksite',
            name='product_used',
        ),
    ]
