# Generated by Django 5.0.2 on 2024-03-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_remove_worksite_product_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
