# Generated by Django 5.0.2 on 2024-03-26 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0030_alter_make_order_amount_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='duty',
            fields=[
                ('duty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('workstation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
            options={
                'db_table': 'duty',
            },
        ),
    ]
