# Generated by Django 5.0.2 on 2024-03-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='payment_method',
            field=models.CharField(default='CASH', max_length=100),
            preserve_default=False,
        ),
    ]
