# Generated by Django 5.0.2 on 2024-03-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0032_make_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='star',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
