# Generated by Django 5.0.2 on 2024-03-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0033_review_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.product'),
        ),
    ]
