# Generated by Django 5.0.2 on 2024-04-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0034_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_allot',
            name='status',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
