# Generated by Django 5.0.2 on 2024-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0035_vehicle_allot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduler',
            fields=[
                ('scheduler_id', models.IntegerField(primary_key=True, serialize=False)),
                ('scheduler_name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scheduler',
            },
        ),
    ]
