# Generated by Django 5.0.2 on 2024-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0037_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photo',
            field=models.FileField(default='abc', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
