# Generated by Django 5.0.2 on 2024-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0040_cart_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail1',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail2',
            new_name='shape',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='detail3',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='detail6',
        ),
    ]
