# Generated by Django 5.0.2 on 2024-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0041_rename_detail1_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strength',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
