# Generated by Django 5.0.2 on 2024-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0042_product_strength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='place',
            new_name='address',
        ),
        migrations.AddField(
            model_name='staff',
            name='pin',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='post',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
