# Generated by Django 5.0.2 on 2024-04-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0043_rename_place_staff_address_staff_pin_staff_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='strength',
        ),
    ]
