# Generated by Django 5.0.2 on 2024-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0044_remove_product_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_order',
            name='month',
            field=models.CharField(default='k', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='make_order',
            name='year',
            field=models.CharField(default='j', max_length=100),
            preserve_default=False,
        ),
    ]
