# Generated by Django 5.0.2 on 2024-04-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0045_make_order_month_make_order_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status2',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
