# Generated by Django 5.0.2 on 2024-04-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0046_staff_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='status2',
        ),
    ]
