# Generated by Django 5.0.2 on 2024-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0047_remove_staff_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhaar',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='dob',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='remark',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
