# Generated by Django 5.0.2 on 2024-04-13 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0048_staff_aadhaar_staff_dob_staff_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='wage',
            fields=[
                ('wage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('wage', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
            options={
                'db_table': 'wage',
            },
        ),
        migrations.DeleteModel(
            name='scheduler',
        ),
    ]
