# Generated by Django 5.0.2 on 2024-04-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0049_wage_delete_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
