# Generated by Django 5.0.2 on 2024-04-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0050_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_slip',
            fields=[
                ('salary_slip_id', models.IntegerField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('leave', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('basic_salary', models.CharField(max_length=100)),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyApp.staff')),
            ],
            options={
                'db_table': 'salary_slip',
            },
        ),
    ]
