# Generated by Django 5.0.2 on 2024-04-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0051_salary_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='month',
            field=models.CharField(default='h', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='year',
            field=models.CharField(default='h', max_length=100),
            preserve_default=False,
        ),
    ]
