# Generated by Django 5.0.2 on 2024-04-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0052_cart_month_cart_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='vehicle',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
